"""Saved-card resource for the MercadoPago API.

The methods in this module map the bearer-authenticated customer card
operations under ``/v1/customers/{customer_id}/cards``. Card token creation is
separate and must be performed client-side with MercadoPago.js.
"""
from mercadopago.core import MPBase


class Card(MPBase):
    """Manages cards saved to a customer profile with an access token."""

    def list_all(self, customer_id, request_options=None):
        """Lists the cards saved for ``customer_id``."""
        return self._get(
            uri=f"/v1/customers/{self._path_param(customer_id)}/cards",
            request_options=request_options,
        )

    def get(self, customer_id, card_id, request_options=None):
        """Gets ``card_id`` from the specified customer profile."""
        return self._get(
            uri=(
                f"/v1/customers/{self._path_param(customer_id)}/cards/"
                f"{self._path_param(card_id)}"
            ),
            request_options=request_options,
        )

    def create(self, customer_id, card_object, request_options=None):
        """Saves a tokenized card to ``customer_id``.

        ``card_object`` is the generic ``SaveCardRequest`` dictionary and must
        contain a token generated by the client-side card-token flow.
        """
        if not isinstance(card_object, dict):
            raise ValueError("Param card_object must be a Dictionary")

        return self._post(
            uri=f"/v1/customers/{self._path_param(customer_id)}/cards",
            data=card_object,
            request_options=request_options,
        )

    def update(self, customer_id, card_id, card_object, request_options=None):
        """Updates a saved card using an ``UpdateCardRequest`` dictionary."""
        if not isinstance(card_object, dict):
            raise ValueError("Param card_object must be a Dictionary")

        return self._put(
            uri=(
                f"/v1/customers/{self._path_param(customer_id)}/cards/"
                f"{self._path_param(card_id)}"
            ),
            data=card_object,
            request_options=request_options,
        )

    def delete(self, customer_id, card_id, request_options=None):
        """Deletes ``card_id`` from the specified customer profile."""
        return self._delete(
            uri=(
                f"/v1/customers/{self._path_param(customer_id)}/cards/"
                f"{self._path_param(card_id)}"
            ),
            request_options=request_options,
        )